DROP DATABASE IF EXISTS POSSystem;
CREATE DATABASE POSSystem;
USE POSSystem;

-- 1. Roles Master Table
CREATE TABLE IF NOT EXISTS roles (
    role_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    active TINYINT(1) DEFAULT 1,
    created_by VARCHAR(255) DEFAULT 'System',
    created_date DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 2. Modules Listing Table
CREATE TABLE IF NOT EXISTS modules (
    module_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

-- 3. Role wise Permissions Matrix
CREATE TABLE IF NOT EXISTS role_permissions (
    role_id INT,
    module_id INT,
    allowed TINYINT(1) DEFAULT 0,
    PRIMARY KEY (role_id, module_id),
    FOREIGN KEY (role_id) REFERENCES roles(role_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (module_id) REFERENCES modules(module_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- 4. Users Table (Linked to Roles)
CREATE TABLE IF NOT EXISTS users (
    user_id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    middle_name VARCHAR(255),
    last_name VARCHAR(255) NOT NULL,
    address_1 VARCHAR(255) NOT NULL,
    address_2 VARCHAR(255),
    address_3 VARCHAR(255),
    city VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL,
    phone_1 VARCHAR(20) NOT NULL,
    phone_2 VARCHAR(20),
    email_1 VARCHAR(255) NOT NULL,
    email_2 VARCHAR(255),
    role_id INT,
    created_by VARCHAR(255) DEFAULT 'System',
    created_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (role_id) REFERENCES roles(role_id) ON DELETE SET NULL ON UPDATE CASCADE
);

-- 5. Customers Table
CREATE TABLE IF NOT EXISTS customers (
    customer_id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    address_1 VARCHAR(255) NOT NULL,
    address_2 VARCHAR(255),
    city VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL,
    phone_1 VARCHAR(20) NOT NULL,
    phone_2 VARCHAR(20),
    email VARCHAR(255) NOT NULL,
    created_by VARCHAR(255) DEFAULT 'System',
    created_date DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 6. Vendors (Suppliers) Table
CREATE TABLE IF NOT EXISTS vendors (
    vendor_id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    company VARCHAR(255),
    address_1 VARCHAR(255) NOT NULL,
    address_2 VARCHAR(255),
    city VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL,
    phone_1 VARCHAR(20) NOT NULL,
    phone_2 VARCHAR(20),
    email VARCHAR(255) NOT NULL,
    created_by VARCHAR(255) DEFAULT 'System',
    created_date DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 7. Units Table
CREATE TABLE IF NOT EXISTS units (
    unit_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    active TINYINT(1) DEFAULT 1,
    created_by VARCHAR(255) DEFAULT 'System',
    created_date DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 8. Taxes Table
CREATE TABLE IF NOT EXISTS taxes (
    tax_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    percentage DECIMAL(5, 2) NOT NULL DEFAULT 0.00,
    active TINYINT(1) DEFAULT 1,
    created_by VARCHAR(255) DEFAULT 'System',
    created_date DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 9. Categories Table
CREATE TABLE IF NOT EXISTS categories (
    category_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    active TINYINT(1) DEFAULT 1,
    created_by VARCHAR(255) DEFAULT 'System',
    created_date DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 10. Items (Products) Table with Advanced Fields
CREATE TABLE IF NOT EXISTS items (
    item_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    short_name VARCHAR(255),
    long_name VARCHAR(255),
    description TEXT,
    code VARCHAR(100),
    image LONGTEXT, -- JSON image path record generated by backend uploads/items, with legacy Base64 support
    sales_price DECIMAL(10, 2) NOT NULL,
    purchase_price DECIMAL(10, 2) NOT NULL,
    editable_price TINYINT(1) DEFAULT 0,
    visible TINYINT(1) DEFAULT 1,
    tax_id INT,
    category_id INT,
    unit_id INT,
    base_quantity DECIMAL(10, 2) DEFAULT 1.00,
    weight_measurement VARCHAR(50) DEFAULT 'none',
    active TINYINT(1) DEFAULT 1,
    created_by VARCHAR(255) DEFAULT 'System',
    created_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (tax_id) REFERENCES taxes(tax_id) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (category_id) REFERENCES categories(category_id) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (unit_id) REFERENCES units(unit_id) ON DELETE SET NULL ON UPDATE CASCADE
);

-- 11. Sales Master (Transaction summary)
CREATE TABLE IF NOT EXISTS sales_master (
    sales_id INT AUTO_INCREMENT PRIMARY KEY,
    customer_id INT NOT NULL,
    sales_date DATE NOT NULL,
    sales_bill_no VARCHAR(100) NOT NULL,
    gross DECIMAL(10, 2) NOT NULL,
    tax DECIMAL(10, 2) NOT NULL,
    total DECIMAL(10, 2) NOT NULL,
    payment_method VARCHAR(50) DEFAULT 'Cash',
    created_by VARCHAR(255) DEFAULT 'System',
    created_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- 12. Sales Details (Transaction line items)
CREATE TABLE IF NOT EXISTS sales_details (
    sales_detail_id INT AUTO_INCREMENT PRIMARY KEY,
    sales_id INT NOT NULL,
    item_id INT NOT NULL,
    rate DECIMAL(10, 2) NOT NULL,
    quantity DECIMAL(10, 2) NOT NULL,
    item_amount DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (sales_id) REFERENCES sales_master(sales_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (item_id) REFERENCES items(item_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- 13. Purchase Master (Transaction summary)
CREATE TABLE IF NOT EXISTS purchase_master (
    purchase_id INT AUTO_INCREMENT PRIMARY KEY,
    vendor_id INT NOT NULL,
    purchase_date DATE NOT NULL,
    purchase_bill_no VARCHAR(100) NOT NULL,
    gross DECIMAL(10, 2) NOT NULL,
    tax DECIMAL(10, 2) NOT NULL,
    total DECIMAL(10, 2) NOT NULL,
    created_by VARCHAR(255) DEFAULT 'System',
    created_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (vendor_id) REFERENCES vendors(vendor_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- 14. Purchase Details (Transaction line items)
CREATE TABLE IF NOT EXISTS purchase_details (
    purchase_detail_id INT AUTO_INCREMENT PRIMARY KEY,
    purchase_id INT NOT NULL,
    item_id INT NOT NULL,
    rate DECIMAL(10, 2) NOT NULL,
    quantity DECIMAL(10, 2) NOT NULL,
    item_amount DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (purchase_id) REFERENCES purchase_master(purchase_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (item_id) REFERENCES items(item_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- SEEDING DATA

-- Seed default roles
INSERT INTO roles (role_id, name, active, created_by) VALUES 
(1, 'Admin', 1, 'System'),
(2, 'Manager', 1, 'System'),
(3, 'User', 1, 'System'),
(4, 'Viewer', 1, 'System');

-- Seed default modules
INSERT INTO modules (module_id, name) VALUES
(1, 'User'),
(2, 'Customer'),
(3, 'Item'),
(4, 'Sales'),
(5, 'Purchase'),
(6, 'Report');

-- Seed role-wise permissions matrix
INSERT INTO role_permissions (role_id, module_id, allowed) VALUES
-- Admin: All checked
(1, 1, 1), (1, 2, 1), (1, 3, 1), (1, 4, 1), (1, 5, 1), (1, 6, 1),
-- Manager: operational masters, billing, and reporting
(2, 1, 0), (2, 2, 1), (2, 3, 1), (2, 4, 1), (2, 5, 1), (2, 6, 1),
-- User: Sales, Purchase checked
(3, 1, 0), (3, 2, 0), (3, 3, 0), (3, 4, 1), (3, 5, 1), (3, 6, 0),
-- Viewer: reporting-only
(4, 1, 0), (4, 2, 0), (4, 3, 0), (4, 4, 0), (4, 5, 0), (4, 6, 1);

-- Seed Default users
INSERT INTO users (user_id, username, password, first_name, middle_name, last_name, address_1, address_2, address_3, city, country, phone_1, phone_2, email_1, email_2, role_id, created_by) VALUES
(1, 'Dhruvi', '8d0f37767e31b16034b9d632edf7402b:40f21b5c7d9d28ce873f25a0551d85f9', 'Dhruvi', '', 'Patel', 'Admin Office 1', '', '', 'Ahmedabad', 'India', '9876543210', '', 'dhruvi@aura.com', '', 1, 'System'),
(2, 'Krinna', '8d0f37767e31b16034b9d632edf7402b:40f21b5c7d9d28ce873f25a0551d85f9', 'Krinna', '', 'Anandpara', 'Manager Desk A', '', '', 'Surat', 'India', '9876543211', '', 'krinna@aura.com', '', 1, 'System'),
(3, 'Parshav', '8d0f37767e31b16034b9d632edf7402b:40f21b5c7d9d28ce873f25a0551d85f9', 'Parshav', '', 'Shah', 'Store Counter 1', '', '', 'Vadodara', 'India', '9876543212', '', 'parshav@aura.com', '', 1, 'System');

-- 15. License Info Table
CREATE TABLE IF NOT EXISTS license_info (
    license_id INT AUTO_INCREMENT PRIMARY KEY,
    license_key VARCHAR(255) NOT NULL,
    valid_from DATE NOT NULL,
    valid_to DATE NOT NULL,
    amc_start_date DATE NOT NULL,
    amc_end_date DATE NOT NULL,
    status VARCHAR(50) DEFAULT 'Active',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Seed default license row
INSERT INTO license_info (license_key, valid_from, valid_to, amc_start_date, amc_end_date, status)
VALUES ('AURA-POS-LICENSE-KEY-2026', '2026-01-01', '2026-08-31', '2026-01-01', '2026-08-31', 'Active');
